version: '3.9'
services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: nodemon src/index.js   # sobrescreve CMD do Dockerfile para dev

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - /app/node_modules    # não mapeia código local, roda só o container
